pipeline:
  use_autoencoder: False
  force_retrain: False

business_targets:
  "business_fp_target": 0.05    # Business False Positive Target
  "threshold_strategy": "f1"    # "f1", "business"

lgbm_params:
  "objective": "binary"
  "metric": ["auc", "average_precision"]
  "boosting_type": "gbdt"
  "learning_rate": 0.07308155218896
  "num_leaves": 36
  "max_depth": 6
  "feature_fraction": 0.592444726907
  "bagging_fraction": 0.761012991294
  "bagging_freq": 5
  "min_gain_to_split": 0.76014646375
  "lambda_l1": 0.3575782827
  "lambda_l2": 3.0075599047387
  "min_data_in_leaf": 100
  "scale_pos_weight": 1.93139122796545
  "verbose": -1

pytorch_params:
  latent_dim: 48
  learning_rate: 4.9817291e-05
  batch_size: 2048
  n_epochs: 150
preprocessing:
  high_cardinality_threshold: 100

train_split:
  train_size: 0.7
  test_size: 0.15