name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install dev tools
        run: |
          pip install pytest pytest-asyncio fakeredis httpx ruff mypy

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Type Check with Mypy
        run: |
          mypy src/ --ignore-missing-imports

      - name: Run tests
        run: |
          pytest -v

      - name: Test Docker Build
        run: |
          docker compose build api-service